### ISSUE TITLE
请教下 反汇编殷勤如何识别全局变量

### ISSUE THREAD

**Issue by taodaqiao** [kabeor/Micro-Capstone-Engine-API-Documentation#1]
请教下 反汇编殷勤如何识别全局变量

**Comment by kabeor** [comment]
事实上，反汇编引擎只会根据相应指令集对opcode进行解析，而对于变量来说，全局变量的内存空间在程序编译完成后就确定不变，保存在文件中，因此全局变量所在位置是一个固定的内存地址，在汇编层面，如果看到读写的是一个固定的内存地址，那么这个地址存放的就是全局变量，而局部变量存储在栈空间中。
这样解释你是否理解呢？

**Comment by kabeor** [comment]
> 请教下 反汇编殷勤如何识别全局变量

事实上，反汇编引擎只会根据相应指令集对opcode进行解析，而对于变量来说，全局变量的内存空间在程序编译完成后就确定不变，保存在文件中，因此全局变量所在位置是一个固定的内存地址，在汇编层面，如果看到读写的是一个固定的内存地址，那么这个地址存放的就是全局变量，而局部变量存储在栈空间中。
这样解释你是否理解呢？

**Comment by taodaqiao** [comment]
@kabeor 如何确定 读写的是一个固定地址呢? 64位rip寻址   mem.base==rip  disp.value>0xfffff  rm == 5 mod<3  这样能否准确

**Comment by kabeor** [comment]
> @kabeor 如何确定 读写的是一个固定地址呢? 64位rip寻址 mem.base==rip disp.value>0xfffff rm == 5 mod<3 这样能否准确

读写的例子如下
.text:00404193                 mov     esi, 0x434FD8           ;读
.text:00404199                 mov     0x434FF8, edi           ;写

直接判断传入的是否是地址就可以了

**Comment by taodaqiao** [comment]
@kabeor 比如这些
mov dword ptr ds:[0xFFFFF8016C664E64], eax
mov rax,dword ptr ds:[0xFFFFF8016C664E64]
lea rcx, ds:[0xFFFFF8016C668800]

**Comment by kabeor** [comment]
0xFFFFF8016C664E64如果一开始已经有定值就是全局变量

**Comment by kabeor** [comment]
> @kabeor 比如这些
> mov dword ptr ds:[0xFFFFF8016C664E64], eax
> mov rax,dword ptr ds:[0xFFFFF8016C664E64]
> lea rcx, ds:[0xFFFFF8016C668800]

0xFFFFF8016C664E64如果一开始已经有定值就是全局变量

**Comment by taodaqiao** [comment]
谢谢,还有个问题 像这样 mov        rax, qword ptr [rip + 0x3593c3]的指令,是不是需要自己转换成
mov     rax,qword ptr [fffff8016c627f70]

**Comment by kabeor** [comment]
> [rip + 0x3593c3]

[rip + 0x3593c3]很显然是对rip的偏移，因此如果开了地址随机化后可能每次的绝对地址都不一样，如果只进行静态分析是可以去转换的，具体请看个人需要

**Comment by kabeor** [comment]
> 谢谢,还有个问题 像这样 mov rax, qword ptr [rip + 0x3593c3]的指令,是不是需要自己转换成
> mov rax,qword ptr [fffff8016c627f70]

[rip + 0x3593c3]很显然是对rip的偏移，因此如果开了地址随机化后可能每次的绝对地址都不一样，如果只进行静态分析是可以去转换的，具体请看个人需要
