### ISSUE TITLE
请教下关于添加capstone对新指令的支持

### ISSUE THREAD

**Issue by junchao98** [kabeor/Micro-Capstone-Engine-API-Documentation#2]
hello~
我现在有些新的，对MIPS的拓展指令，在capstone没有对这些指令的支持，我想增加这些新指令支持，是需要在MipsGenDisassemblerTables.inc文件新建DecoderTable来描述这些指令吗（看见文件注释说这些DecoderTable是自动生成的），
现在对DecoderTable某些字段意义不太明白，想请教下，例如在MipsGenDisassemblerTables.inc文件中 27行
static uint8_t DecoderTableCOP3_32[] = {
/* 0 */       MCD_OPC_ExtractField, 26, 6,  // Inst{31-26} ...
/* 3 */       MCD_OPC_FilterValue, 51, 8, 0, // Skip to: 15
/* 7 */       MCD_OPC_CheckPredicate, 1, 40, 0, // Skip to: 51
/* 11 */      MCD_OPC_Decode, 220, 7, 10, // Opcode: LWC3
/* 15 */      MCD_OPC_FilterValue, 55, 8, 0, // Skip to: 27
/* 19 */      MCD_OPC_CheckPredicate, 2, 28, 0, // Skip to: 51
/* 23 */      MCD_OPC_Decode, 167, 7, 10, // Opcode: LDC3
/* 27 */      MCD_OPC_FilterValue, 59, 8, 0, // Skip to: 39
/* 31 */      MCD_OPC_CheckPredicate, 1, 16, 0, // Skip to: 51
/* 35 */      MCD_OPC_Decode, 242, 12, 10, // Opcode: SWC3
/* 39 */      MCD_OPC_FilterValue, 63, 8, 0, // Skip to: 51
/* 43 */      MCD_OPC_CheckPredicate, 2, 4, 0, // Skip to: 51
/* 47 */      MCD_OPC_Decode, 161, 11, 10, // Opcode: SDC3
/* 51 */      MCD_OPC_Fail,
  0
};
在6915行中 
    case MCD_OPC_Decode: { \
      Opc = (unsigned)decodeULEB128(++Ptr, &Len); \
      Ptr += Len; \
      DecodeIdx = (unsigned)decodeULEB128(Ptr, &Len); \
      Ptr += Len; \
      MCInst_setOpcode(MI, Opc); \
      return decoder(S, DecodeIdx, insn, MI, Address, MRI); \
    } \
对数组MCD_OPC_Decode字段进行读取，但对/* 11 */      MCD_OPC_Decode, 220, 7, 10, // Opcode: LWC3 中的220，7，10的含义不明白，220似乎是mips.h 里mips_insn中MIPS_INS_SDC3 的值，不知您对capstone对mips反汇编过程了解吗，或者是否有相关资料，望赐教。

**Comment by kabeor** [comment]
> hello~
> 我现在有些新的，对MIPS的拓展指令，在capstone没有对这些指令的支持，我想增加这些新指令支持，是需要在MipsGenDisassemblerTables.inc文件新建DecoderTable来描述这些指令吗（看见文件注释说这些DecoderTable是自动生成的），
> 现在对DecoderTable某些字段意义不太明白，想请教下，例如在MipsGenDisassemblerTables.inc文件中 27行
> static uint8_t DecoderTableCOP3_32[] = {
> /* 0 _/ MCD_OPC_ExtractField, 26, 6, // Inst{31-26} ... /_ 3 _/ MCD_OPC_FilterValue, 51, 8, 0, // Skip to: 15 /_ 7 _/ MCD_OPC_CheckPredicate, 1, 40, 0, // Skip to: 51 /_ 11 _/ MCD_OPC_Decode, 220, 7, 10, // Opcode: LWC3 /_ 15 _/ MCD_OPC_FilterValue, 55, 8, 0, // Skip to: 27 /_ 19 _/ MCD_OPC_CheckPredicate, 2, 28, 0, // Skip to: 51 /_ 23 _/ MCD_OPC_Decode, 167, 7, 10, // Opcode: LDC3 /_ 27 _/ MCD_OPC_FilterValue, 59, 8, 0, // Skip to: 39 /_ 31 _/ MCD_OPC_CheckPredicate, 1, 16, 0, // Skip to: 51 /_ 35 _/ MCD_OPC_Decode, 242, 12, 10, // Opcode: SWC3 /_ 39 _/ MCD_OPC_FilterValue, 63, 8, 0, // Skip to: 51 /_ 43 _/ MCD_OPC_CheckPredicate, 2, 4, 0, // Skip to: 51 /_ 47 _/ MCD_OPC_Decode, 161, 11, 10, // Opcode: SDC3 /_ 51 _/ MCD_OPC_Fail, 0 }; 在6915行中 case MCD_OPC_Decode: { Opc = (unsigned)decodeULEB128(++Ptr, &Len); Ptr += Len; DecodeIdx = (unsigned)decodeULEB128(Ptr, &Len); Ptr += Len; MCInst_setOpcode(MI, Opc); return decoder(S, DecodeIdx, insn, MI, Address, MRI); } 对数组MCD_OPC_Decode字段进行读取，但对/_ 11 */ MCD_OPC_Decode, 220, 7, 10, // Opcode: LWC3 中的220，7，10的含义不明白，220似乎是mips.h 里mips_insn中MIPS_INS_SDC3 的值，不知您对capstone对mips反汇编过程了解吗，或者是否有相关资料，望赐教。

Hello, 你应该在
https://github.com/aquynh/capstone/blob/e5bb1186063ba41ddeed52e5638fa859abf35e18/arch/Mips/MipsMapping.c#L255 
添加自己的指令，当然，也有可能需要扩充下面的group_name_maps。然后需要定位到Mips的decodeInstruction对你要增加对指令进行逻辑编写。具体问题还请到capstone提issue，相信Nguyen教授会给出更精准的解答。

**Comment by junchao-loongson** [comment]
> > hello~
> > 我现在有些新的，对MIPS的拓展指令，在capstone没有对这些指令的支持，我想增加这些新指令支持，是需要在MipsGenDisassemblerTables.inc文件新建DecoderTable来描述这些指令吗（看见文件注释说这些DecoderTable是自动生成的），
> > 现在对DecoderTable某些字段意义不太明白，想请教下，例如在MipsGenDisassemblerTables.inc文件中 27行
> > static uint8_t DecoderTableCOP3_32[] = {
> > /* 0 _/ MCD_OPC_ExtractField, 26, 6, // Inst{31-26} ... /_ 3 _/ MCD_OPC_FilterValue, 51, 8, 0, // Skip to: 15 /_ 7 _/ MCD_OPC_CheckPredicate, 1, 40, 0, // Skip to: 51 /_ 11 _/ MCD_OPC_Decode, 220, 7, 10, // Opcode: LWC3 /_ 15 _/ MCD_OPC_FilterValue, 55, 8, 0, // Skip to: 27 /_ 19 _/ MCD_OPC_CheckPredicate, 2, 28, 0, // Skip to: 51 /_ 23 _/ MCD_OPC_Decode, 167, 7, 10, // Opcode: LDC3 /_ 27 _/ MCD_OPC_FilterValue, 59, 8, 0, // Skip to: 39 /_ 31 _/ MCD_OPC_CheckPredicate, 1, 16, 0, // Skip to: 51 /_ 35 _/ MCD_OPC_Decode, 242, 12, 10, // Opcode: SWC3 /_ 39 _/ MCD_OPC_FilterValue, 63, 8, 0, // Skip to: 51 /_ 43 _/ MCD_OPC_CheckPredicate, 2, 4, 0, // Skip to: 51 /_ 47 _/ MCD_OPC_Decode, 161, 11, 10, // Opcode: SDC3 /_ 51 _/ MCD_OPC_Fail, 0 }; 在6915行中 case MCD_OPC_Decode: { Opc = (unsigned)decodeULEB128(++Ptr, &Len); Ptr += Len; DecodeIdx = (unsigned)decodeULEB128(Ptr, &Len); Ptr += Len; MCInst_setOpcode(MI, Opc); return decoder(S, DecodeIdx, insn, MI, Address, MRI); } 对数组MCD_OPC_Decode字段进行读取，但对/_ 11 */ MCD_OPC_Decode, 220, 7, 10, // Opcode: LWC3 中的220，7，10的含义不明白，220似乎是mips.h 里mips_insn中MIPS_INS_SDC3 的值，不知您对capstone对mips反汇编过程了解吗，或者是否有相关资料，望赐教。
> 
> Hello, 你应该在
> https://github.com/aquynh/capstone/blob/e5bb1186063ba41ddeed52e5638fa859abf35e18/arch/Mips/MipsMapping.c#L255
> 添加自己的指令，当然，也有可能需要扩充下面的group_name_maps。然后需要定位到Mips的decodeInstruction对你要增加对指令进行逻辑编写。具体问题还请到capstone提issue，相信Nguyen教授会给出更精准的解答。

非常感谢您的解答！
